version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  ci_skip_check:
    executor:
      name: node/default
    steps:
      - run:
          command: |
            NEW_COMMITS=$(git log --since=1.minutes)
            if !NEW_COMMITS; then
              circleci-agent step halt
            fi
workflows:
  nightly:
    triggers:
      - schedule:
          cron: "* * * * *" # 12am CET
          filters:
            branches:
              only:
                - circleci-project-setup
    jobs:
      - ci_skip_check
      - build-and-test
