version: 2.0
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo $COMPARE_URL
            
workflows:
#  when: << pipeline.git.revision != pipeline.git.base_revision	>>
  nightly:
    triggers:
      - schedule:
          cron: "* * * * *" # 12am CET
          filters:
            branches:
              only:
                - master
    jobs:
      - build-and-test
