version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                command: |
                  echo << pipeline.id                 >>
                  echo << pipeline.number             >>
                  echo << pipeline.project.git_url    >>
                  echo << pipeline.project.type       >>
                  echo << pipeline.git.tag            >>
                  echo << pipeline.git.branch         >>
                  echo << pipeline.git.revision       >>
                  echo << pipeline.git.base_revision  >>
            - run: npm install
            - run: npm test
workflows:
#  when: << pipeline.git.revision != pipeline.git.base_revision	>>
  nightly:
    triggers:
      - schedule:
          cron: "* * * * *" # 12am CET
          filters:
            branches:
              only:
                - circleci-project-setup
    jobs:
      - build-and-test
