version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
  nightly:
    triggers:
      - schedule:
          cron: "1 * * * *"
          filters:
            branches:
              only:
                - circleci-project-setup
    when:
      not:
        equal: [CIRCLE_SHA1, LAST_RUN_COMMIT]
    jobs:
      - build-and-test
